<?php

/**
 * @file
 * Contains video_bg.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function video_bg_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the video_bg module.
    case 'help.page.video_bg':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display videos as background elements.') . '</p>';
      return $output;

    default:
  }
}
